language: elixir
elixir:
  - 1.6

install:
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y inotify-tools
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - (cd example && mix deps.get && cd assets && npm install)
  - cd ..

before_script:
  - phantomjs -w &

script: mix test && cd example && WALLABY_DRIVER=phantom MIX_ENV=test && (cd assets && npm run deploy) && mix compile && mix test
