language: elixir
elixir:
  - 1.2.2

addons:
  apt:
    packages:
    - nodejs

before_script:
  - phantomjs -w &

script: mix test && cd example && mix deps.get && npm install && WEBDRIVER=phantomjs MIX_ENV=test mix compile && mix test
